# Generated by Django 3.2.8 on 2022-12-11 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenIngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado Ingreso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('farmaceuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Orden de Ingreso de Producto',
                'verbose_name_plural': 'Ordenes de Ingresos de Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoMermado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Mermada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('motivo', models.CharField(choices=[('NO ESPECIFICADO', 'No Especificado'), ('VENCIMIENTO', 'Vencimiento'), ('CANJE', 'Canje'), ('DETERIORO', 'Deterioro'), ('MERMA', 'Merma'), ('PRESTAMOS', 'Préstamos'), ('OTRO', 'Otro')], default='NO ESPECIFICADO', max_length=100, verbose_name='Motivo')),
                ('farmaceuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Mermado',
                'verbose_name_plural': 'Productos Mermados',
            },
        ),
        migrations.CreateModel(
            name='ProductoIngresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada al Stock')),
                ('lote', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Lote')),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Compra Producto')),
                ('precio_venta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Venta Producto')),
                ('n_factura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de factura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('n_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ordeningresoproducto')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Ingresado',
                'verbose_name_plural': 'Productos Ingresados',
                'ordering': ['-n_venta'],
            },
        ),
        migrations.CreateModel(
            name='BodegaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock del producto')),
                ('stock_min', models.IntegerField(blank=True, null=True, verbose_name='Stock minimo del producto')),
                ('stock_max', models.IntegerField(blank=True, null=True, verbose_name='Stock maximo del producto')),
                ('holgura', models.IntegerField(blank=True, null=True, verbose_name='Holgura del Stock')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Bodega Virtual',
                'verbose_name_plural': 'Bodega Virtual',
                'db_table': 'BodegaVirtual',
            },
        ),
    ]
