# Generated by Django 3.2.8 on 2022-10-21 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0008_auto_20221021_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Laboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='OrdenIngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Orden de Ingreso de Producto',
                'verbose_name_plural': 'Ordenes de Ingresos de Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoIngresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Vendida')),
                ('proveedor', models.CharField(blank=True, max_length=25, null=True, verbose_name='Proveedor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('farmaceuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.laboratorios', verbose_name='Nombre Producto')),
                ('n_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ordeningresoproducto')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Ingresado',
                'verbose_name_plural': 'Productos Ingresados',
                'ordering': ['-n_venta'],
            },
        ),
        migrations.CreateModel(
            name='BodegaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock del producto')),
                ('stock_min', models.IntegerField(blank=True, null=True, verbose_name='Stock minimo del producto')),
                ('stock_max', models.IntegerField(blank=True, null=True, verbose_name='Stock maximo del producto')),
                ('holgura', models.IntegerField(blank=True, null=True, verbose_name='Holgura del Stock')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Bodega Virtual',
                'verbose_name_plural': 'Bodega Virtual',
                'db_table': 'BodegaVirtual',
            },
        ),
    ]
