# Generated by Django 3.2.8 on 2022-12-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_recetas_comprobante_venta'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenIngresoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingresada', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada al Stock')),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Compra Producto')),
                ('precio_venta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Venta Producto')),
                ('n_lote', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Lote')),
                ('n_factura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
        ),
    ]
