# Generated by Django 3.2.8 on 2022-10-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_productomermado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoingresado',
            name='precio_compra',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Compra Producto'),
        ),
    ]
