# Generated by Django 3.2.8 on 2022-10-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_productoingresado_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordeningresoproducto',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='productoingresado',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada al Stock'),
        ),
        migrations.AlterField(
            model_name='productoingresado',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.laboratorios', verbose_name='Laboratorio'),
        ),
    ]
