# Generated by Django 3.2.8 on 2022-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20221027_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomermado',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Mermada'),
        ),
    ]
