# Generated by Django 3.2.8 on 2022-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_ordeningresoproducto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoingresado',
            name='cenabast',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cenabast'),
        ),
    ]
