# Generated by Django 3.2.8 on 2022-11-09 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0008_productoingresado_cenabast'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeningresoproducto',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
    ]
