# Generated by Django 3.2.8 on 2022-11-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0008_productoingresado_cenabast'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeningresoproducto',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='productomermado',
            name='motivo',
            field=models.CharField(blank=True, choices=[('NO ESPECIFICADO', 'No Especificado'), ('VENCIMIENTO', 'Vencimiento'), ('CANJE', 'Canje'), ('DETERIORO', 'Deterioro'), ('MERMA', 'Merma'), ('PRESTAMOS', 'Préstamos'), ('OTRO', 'Otro')], default='NO ESPECIFICADO', max_length=100, verbose_name='Motivo'),
        ),
    ]
