# Generated by Django 3.2.8 on 2022-11-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20221121_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoingresado',
            name='cenabast',
        ),
        migrations.RemoveField(
            model_name='productoingresado',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='productoingresado',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='productoingresado',
            name='precio_venta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Venta Producto'),
        ),
    ]
