# Generated by Django 3.2.8 on 2022-11-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20221122_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratorios',
        ),
    ]
