# Generated by Django 3.2.8 on 2022-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_delete_laboratorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoingresado',
            name='lote',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Lote'),
        ),
        migrations.AlterField(
            model_name='productomermado',
            name='motivo',
            field=models.CharField(choices=[('NO ESPECIFICADO', 'No Especificado'), ('VENCIMIENTO', 'Vencimiento'), ('CANJE', 'Canje'), ('DETERIORO', 'Deterioro'), ('MERMA', 'Merma'), ('PRESTAMOS', 'Préstamos'), ('OTRO', 'Otro')], default='NO ESPECIFICADO', max_length=100, verbose_name='Motivo'),
        ),
    ]
