# Generated by Django 3.2.8 on 2022-12-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0013_auto_20221201_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegavirtual',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock del producto'),
        ),
        migrations.AddField(
            model_name='bodegavirtual',
            name='stock_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock maximo del producto'),
        ),
        migrations.AddField(
            model_name='bodegavirtual',
            name='stock_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock minimo del producto'),
        ),
        migrations.AddField(
            model_name='ordeningresoproducto',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='productoingresado',
            name='n_factura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de factura'),
        ),
    ]
