# Generated by Django 3.1.7 on 2021-02-22 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=20, verbose_name='Direccion')),
                ('uv', models.PositiveSmallIntegerField(verbose_name='Unidad vecinal')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Numero de casa')),
                ('calle', models.CharField(max_length=30, verbose_name='Nombre de la calle')),
                ('pc', models.PositiveIntegerField(blank=True, verbose_name='Codigo Postal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['uv'],
            },
        ),
        migrations.CreateModel(
            name='FormularioBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(default='datalake', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulario base',
                'verbose_name_plural': 'formularios bases',
                'ordering': ['-created'],
            },
        ),
    ]
