# Generated by Django 3.1.7 on 2021-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pc',
            field=models.PositiveIntegerField(verbose_name='Codigo Postal'),
        ),
    ]
