# Generated by Django 3.1.7 on 2021-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20210226_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallesCondiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('condiciones', models.TextField()),
            ],
            options={
                'ordering': ['calle'],
            },
        ),
        migrations.AlterField(
            model_name='formulariobase',
            name='texto1',
            field=models.TextField(blank=True, verbose_name='Texto 1'),
        ),
        migrations.AlterField(
            model_name='formulariobase',
            name='texto2',
            field=models.TextField(blank=True, verbose_name='Texto 2'),
        ),
        migrations.AlterField(
            model_name='formulariobase',
            name='texto3',
            field=models.TextField(blank=True, verbose_name='Texto 3'),
        ),
        migrations.AlterField(
            model_name='formulariobase',
            name='texto4',
            field=models.TextField(blank=True, verbose_name='Texto 4'),
        ),
    ]
