# Generated by Django 3.1.7 on 2021-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20210226_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['-nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='callescondiciones',
            options={'ordering': ['calle'], 'verbose_name': 'Calle y UV', 'verbose_name_plural': 'Calles y UV'},
        ),
        migrations.RenameField(
            model_name='formulariobase',
            old_name='nacionalidad',
            new_name='p_origen',
        ),
    ]
