# Generated by Django 3.1.7 on 2021-03-02 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20210226_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariobase',
            old_name='rut',
            new_name='numero_identificacion',
        ),
        migrations.AddField(
            model_name='formulariobase',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariobase',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Rut', 'Rut'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='formulariobase',
            name='numero_casa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
