# Generated by Django 3.1.7 on 2021-03-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20210302_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariobase',
            old_name='numero_casa',
            new_name='numero_calle',
        ),
    ]
