# Generated by Django 3.1.7 on 2021-03-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_auto_20210303_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariobase',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='formulariobase',
            name='uv',
            field=models.IntegerField(default=0),
        ),
    ]
