# Generated by Django 3.1.7 on 2021-03-09 20:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0009_auto_20210303_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariobase',
            name='autor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
