# Generated by Django 3.1.7 on 2021-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_auto_20210310_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariobase',
            name='apellido',
            field=models.CharField(default='', max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='formulariobase',
            name='nombre',
            field=models.CharField(default='', max_length=30, verbose_name='Nombres'),
        ),
    ]
