# Generated by Django 3.1.7 on 2021-03-23 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0016_formularioomil_nombre_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombres')),
                ('apellido', models.CharField(default='', max_length=30, verbose_name='Apellidos')),
                ('c_telefono', models.PositiveIntegerField(blank=True, default='569', verbose_name='Codigo de Telefono')),
                ('n_telefono', models.CharField(blank=True, default='11111111', max_length=30, verbose_name='Numero de Telefono')),
                ('direccion', models.CharField(blank=True, default='', max_length=30, verbose_name='Nombre de Calle')),
                ('numero_calle', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Casa')),
                ('complemento_direccion', models.TextField(blank=True, verbose_name='Complemento Direccion')),
                ('res_denuncia', models.TextField(blank=True, verbose_name='Resumen de la Denuncia')),
                ('tipi_reclamo', models.CharField(blank=True, max_length=30, verbose_name='Tipificacion Reclamo')),
                ('tipi_denuncia', models.TextField(blank=True, verbose_name='Tipificacion Denuncias')),
                ('cuadrante', models.PositiveIntegerField(blank=True, verbose_name='Cuadrante')),
                ('n_movil', models.CharField(blank=True, max_length=30, verbose_name='Numero de Movil')),
                ('emergencias', models.TextField(blank=True, verbose_name='Emergencias')),
                ('derv_emergencias', models.CharField(blank=True, max_length=30, verbose_name='Derivaciones de Emergencias')),
                ('des_caso', models.TextField(blank=True, verbose_name='Descripcion Caso')),
                ('iden_carab', models.CharField(blank=True, max_length=30, verbose_name='Identificacion Carabineros')),
                ('iden_aav', models.CharField(blank=True, max_length=30, verbose_name='Identificacion AAV')),
                ('departamento', models.CharField(blank=True, max_length=30, verbose_name='Departamento')),
                ('inf_general', models.TextField(blank=True, verbose_name='Informacion General')),
                ('nombre_formulario', models.CharField(default='Formulario Seguridad', editable=False, max_length=20)),
                ('uv', models.IntegerField(default=0, verbose_name='Unidad Vecinal')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulario seguridad',
                'verbose_name_plural': 'formularios de seguridad',
                'ordering': ['-created'],
            },
        ),
    ]
