# Generated by Django 3.1.7 on 2021-03-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0017_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('numero_identificacion', models.CharField(default='', max_length=30)),
                ('tipo_identificacion', models.CharField(choices=[('RUT', 'RUT'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombres')),
                ('apellido', models.CharField(default='', max_length=30, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, default='', max_length=30, verbose_name='Nombre de Calle')),
                ('numero_calle', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Casa')),
                ('n_ficha', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Ficha')),
                ('complemento_direccion', models.TextField(blank=True, verbose_name='Complemento Direccion')),
                ('c_telefono', models.PositiveIntegerField(blank=True, default='569', verbose_name='Codigo de Telefono')),
                ('n_telefono', models.CharField(blank=True, default='11111111', max_length=30, verbose_name='Numero de Telefono')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=10, verbose_name='Fecha de Nacimiento')),
                ('sis_salud', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('NINGUNO', 'NINGUNO'), ('OTRO', 'OTRO')], default='', max_length=30)),
                ('estado_civil', models.CharField(choices=[('SOLTERA/O', 'SOLTERA/O'), ('CASADA/O', 'CASADA/O'), ('CONVIVIENTE CIVIL', 'CONVIVIENTE CIVIL'), ('VIUDA/O', 'VIUDA/O'), ('DIVORCIADA/O', 'DIVORCIADA/O')], default='', max_length=30)),
                ('numero_hijos', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Hijos')),
                ('p_origen', models.CharField(default='', max_length=30, verbose_name='Pais de Origen')),
                ('email_form', models.EmailField(blank=True, max_length=30, verbose_name='Direccion de Email')),
                ('enfermedad', models.CharField(default='', max_length=30, verbose_name='Enfermedad')),
                ('med_uso_per', models.CharField(default='', max_length=30, verbose_name='Medicamentos de Uso Permanente')),
                ('lugar_atencion', models.CharField(choices=[('CESFAM CRUZ MELO', 'CESFAM CRUZ MELO'), ('CESFAM JUAN ANTONIO RÍOS', 'CESFAM JUAN ANTONIO RÍOS')], default='', max_length=30)),
                ('discapacidad', models.BooleanField(blank=True, verbose_name='Posee Discapacidad')),
                ('discapacidad_doc', models.FileField(blank=True, upload_to='farmacia/discapacidad/%Y/%m/', verbose_name='Documento de Discapacidad')),
                ('embarazo', models.BooleanField(blank=True, verbose_name='Esta Embarazada')),
                ('embarazo_doc', models.FileField(blank=True, upload_to='farmacia/embarazo/%Y/%m/', verbose_name='Documento de Embarazo')),
                ('nombre_formulario', models.CharField(default='Formulario Farmacia', editable=False, max_length=20)),
                ('uv', models.IntegerField(default=0, verbose_name='Unidad Vecinal')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulario farmacia',
                'verbose_name_plural': 'formularios de farmacias',
                'ordering': ['-created'],
            },
        ),
    ]
