# Generated by Django 3.1.7 on 2021-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0019_auto_20210420_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariobase',
            name='nombre_formulario',
            field=models.CharField(default='Formulario Base', editable=False, max_length=20),
        ),
    ]
