# Generated by Django 3.1.7 on 2021-04-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0021_auto_20210420_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(default='Denuncias', editable=False, max_length=20)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estatus')),
                ('tipo_identificacion_denunciante', models.CharField(choices=[('Rut', 'Rut'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='Rut', max_length=30, verbose_name='Tipo de Documento Denunciante')),
                ('numero_identificacion_denunciante', models.CharField(blank=True, default='', max_length=30, verbose_name='Numero de Documento Denunciante')),
                ('nombre_denunciante', models.CharField(default='', max_length=30, verbose_name='Nombres Denunciante')),
                ('apellido_p_denunciante', models.CharField(default='', max_length=30, verbose_name='Apellido Paterno Denunciante')),
                ('apellido_m_denunciante', models.CharField(blank=True, default='', max_length=30, verbose_name='Apellidos Materno Denunciante')),
                ('telefono_denunciante', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefono Denunciante')),
                ('direccion', models.CharField(default='', max_length=30, verbose_name='Calle Denunciante')),
                ('numero_calle', models.PositiveIntegerField(default=0, verbose_name='Numero Calle Denunciante')),
                ('email_denunciante', models.EmailField(blank=True, max_length=30, verbose_name='Email de Contacto Denunciante')),
                ('tipo_denuncia', models.CharField(choices=[('Zoonosis', 'Zoonosis'), ('TRM', 'TRM'), ('Higene Ambiental', 'Higene Ambiental')], default='', max_length=30, verbose_name='Tipo de denuncia')),
                ('texto_denuncia', models.TextField(blank=True, verbose_name='Texto de Denuncia')),
                ('nombre_denunciado', models.CharField(blank=True, default='', max_length=30, verbose_name='Nombres Denunciante')),
                ('apellido_p_denunciado', models.CharField(blank=True, default='', max_length=30, verbose_name='Apellido Paterno Denunciado')),
                ('apellido_m_denunciado', models.CharField(blank=True, default='', max_length=30, verbose_name='Apellidos Materno Denunciado')),
                ('telefono_denunciado', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefono Denunciado')),
                ('direccion_denunciado', models.CharField(blank=True, default='', max_length=30, verbose_name='Calle Denunciado')),
                ('numero_calle_denunciado', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero Calle Denunciado')),
                ('email_denunciado', models.EmailField(blank=True, max_length=30, verbose_name='Email de Contacto Denunciado')),
                ('fecha_visita', models.DateField(auto_now_add=True, verbose_name='Fecha de Visita Inspectiva')),
                ('lugar_de_transgresion', models.CharField(choices=[('Via Publica', 'Via Publica'), ('Domicilio', 'Domicilio')], default='', max_length=30, verbose_name='Lugar de Transgrecion')),
                ('visita_inspectiva', models.CharField(choices=[('Inspector', 'Inspector'), ('Profesional', 'Profesional')], default='', max_length=30, verbose_name='Tipo de Visita Inspectiva')),
                ('texto_observacion', models.TextField(blank=True, verbose_name='Texto de Denuncia')),
                ('categoria_visita', models.CharField(choices=[('Se Visita. Hay Contacto', 'Se Visita. Hay Contacto'), ('Se Visita. No Hay Contacto', 'Se Visita. No Hay Contacto'), ('Otra', 'Otra')], default='', max_length=30, verbose_name='Categoria de Visita Inspectiva')),
                ('notificacion', models.CharField(choices=[('Con Notificacion', 'Con Notificacion'), ('Sin Notificacion', 'Sin Notificacion')], default='', max_length=30, verbose_name='Notificacion')),
                ('numero_noficacion', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Notificacion')),
                ('texto_enviado', models.TextField(blank=True, verbose_name='Texto Respuesta Enviado')),
                ('ver_respuesta', models.ImageField(blank=True, upload_to='verificacion_denuncias')),
                ('uv_denunciante', models.IntegerField(default=0)),
                ('uv_denunciado', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-created'],
            },
        ),
    ]
