# Generated by Django 3.1.7 on 2021-04-20 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0022_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_visita',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de Visita Inspectiva'),
        ),
    ]
