# Generated by Django 3.1.7 on 2021-04-20 23:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0023_auto_20210420_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='uv_denunciante',
            new_name='uv',
        ),
        migrations.CreateModel(
            name='ControlDePlaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(default='Control de Plagas', editable=False, max_length=20)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estatus')),
                ('ficha_numero', models.PositiveIntegerField(blank=True, default=0, verbose_name='Numero de Ficha')),
                ('tipo_identificacion', models.CharField(choices=[('Rut', 'Rut'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='Rut', max_length=30, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, default='', max_length=30, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombres')),
                ('apellido_p', models.CharField(default='', max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(blank=True, default='', max_length=30, verbose_name='Apellidos Materno')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefono')),
                ('direccion', models.CharField(default='', max_length=30, verbose_name='Calle')),
                ('numero_calle', models.PositiveIntegerField(default=0, verbose_name='Numero Calle')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email de Contacto')),
                ('tipo_solicitud', models.CharField(choices=[('Desratizar', 'Desratizar'), ('Fumigar', 'Fumigar'), ('Sanitizar', 'Sanitizar')], default='', max_length=30, verbose_name='Tipo de Solicitud')),
                ('fecha_coordinada', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha Coordinada')),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default='', max_length=30, verbose_name='Jornada de Servicio')),
                ('fecha_visita', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha Operacion')),
                ('producto', models.CharField(choices=[('RATAMIX', 'RATAMIX'), ('DELTA MAX', 'DELTA MAX'), ('DUPLALIM', 'DUPLALIM')], default='', max_length=30, verbose_name='Producto Utilizado')),
                ('uv', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Plaga',
                'verbose_name_plural': 'Controles de Plagas',
                'ordering': ['-created'],
            },
        ),
    ]
