# Generated by Django 3.1.7 on 2021-04-20 23:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0024_auto_20210420_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esterilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(default='Esterilizacion', editable=False, max_length=20)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Anulado', 'Anulado')], default='Pendiente', max_length=30, verbose_name='Estatus')),
                ('tipo_identificacion', models.CharField(choices=[('Rut', 'Rut'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='Rut', max_length=30, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, default='', max_length=30, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombres')),
                ('apellido_p', models.CharField(default='', max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(blank=True, default='', max_length=30, verbose_name='Apellidos Materno')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefono')),
                ('direccion', models.CharField(default='', max_length=30, verbose_name='Calle')),
                ('numero_calle', models.PositiveIntegerField(default=0, verbose_name='Numero Calle')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email de Contacto')),
                ('mascota', models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino')], default='', max_length=30, verbose_name='Especie Mascota')),
                ('nombre_mascota', models.CharField(default='', max_length=30, verbose_name='Nombre Mascota')),
                ('sexo_mascota', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=30, verbose_name='Sexo de Mascota')),
                ('fecha_cirugia', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha Coordinada')),
                ('clinica', models.CharField(choices=[('Municipal (movil)', 'Municipal (movil)'), ('Particular', 'Particular')], default='', max_length=30, verbose_name='Tipo de Clinica')),
                ('asistencia', models.CharField(choices=[('Asiste', 'Asiste'), ('No Asiste', 'No Asiste'), ('Pendiente de Hora', 'Pendiente de Hora')], default='', max_length=30, verbose_name='Producto Utilizado')),
                ('rechazo', models.TextField(blank=True, verbose_name='Motivo Rechazo')),
                ('uv', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esterilizacion',
                'verbose_name_plural': 'Esterilizaciones',
                'ordering': ['-created'],
            },
        ),
    ]
