# Generated by Django 3.2.1 on 2021-05-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0025_esterilizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlDePlaga',
        ),
    ]
