# Generated by Django 3.2.1 on 2021-05-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0027_controldeplaga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paises',
            options={'ordering': ['nombre'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.RemoveField(
            model_name='controldeplaga',
            name='fecha_coordinada',
        ),
        migrations.RemoveField(
            model_name='controldeplaga',
            name='fecha_visita',
        ),
    ]
