# Generated by Django 3.2.1 on 2021-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0028_auto_20210504_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldeplaga',
            name='fecha_coordinada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Coordinada'),
        ),
        migrations.AddField(
            model_name='controldeplaga',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Operacion'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_visita',
            field=models.DateField(blank=True, verbose_name='Fecha de Visita Inspectiva'),
        ),
        migrations.AlterField(
            model_name='esterilizacion',
            name='fecha_cirugia',
            field=models.DateField(blank=True, verbose_name='Fecha Coordinada'),
        ),
    ]
