# Generated by Django 3.2.1 on 2021-07-08 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0029_auto_20210511_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controldeplaga',
            name='fecha_coordinada',
        ),
        migrations.RemoveField(
            model_name='controldeplaga',
            name='fecha_visita',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_visita',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de Visita Inspectiva'),
        ),
        migrations.AlterField(
            model_name='esterilizacion',
            name='fecha_cirugia',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha Coordinada'),
        ),
    ]
