# Generated by Django 3.2.8 on 2021-12-21 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/empresas/', verbose_name='Empresas')),
            ],
        ),
        migrations.CreateModel(
            name='CargaEntregasPandemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/pandemia/', verbose_name='Entrega Pandemia')),
            ],
        ),
        migrations.CreateModel(
            name='CargaPatentesVehiculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/patentes_vehiculares/', verbose_name='Patentes Vehiculares')),
            ],
        ),
        migrations.CreateModel(
            name='CargaPermisosCirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/permiso_circulacion/', verbose_name='Permisos Circulacion')),
            ],
        ),
        migrations.CreateModel(
            name='PermisosCirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('rut', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidad')),
                ('nombres', models.CharField(blank=True, max_length=30, verbose_name='Nombres')),
                ('efectuo_tramite', models.CharField(blank=True, max_length=30, verbose_name='Efectuo Tramite')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
        migrations.CreateModel(
            name='PatentesVehiculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_fabricacion', models.PositiveIntegerField(verbose_name='Trabajadores pais')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del auto')),
                ('placa', models.CharField(max_length=30, verbose_name='Placa')),
                ('calle', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numeracion', models.PositiveIntegerField(verbose_name='Numeracion')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo del auto')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('codigo_sii', models.CharField(max_length=30, verbose_name='Codigo de SII')),
                ('forma_pago', models.CharField(choices=[('1RA CUOTA', '1er cuota'), ('2DA CUOTA', '2da cuota'), ('CONTADO', 'Contado'), ('OTRO', 'Otro')], default='', max_length=30, null=True, verbose_name='Forma de pago')),
                ('total_pagar', models.PositiveIntegerField(verbose_name='Total a Pagar')),
                ('año_permiso', models.PositiveIntegerField(verbose_name='Año de Permiso')),
                ('fecha_pago', models.DateField(verbose_name='fecha de Pago')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
        migrations.CreateModel(
            name='EntregasPandemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.PositiveIntegerField(verbose_name='Número ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_identificacion', models.CharField(choices=[('RUT', 'Rut'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='RUT', max_length=30, verbose_name='Tipo de Documento')),
                ('nombre_persona', models.CharField(max_length=30, verbose_name='Nombre Persona')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=30, null=True, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('complemento_direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento de Dirección')),
                ('caja_mercaderia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Caja Mercaderia')),
                ('pañal_adulto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pañal Adulto')),
                ('pañal_niño_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pañal niño talla M')),
                ('pañal_niño_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pañal niño talla G')),
                ('pañal_niño_xg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pañal niño talla XG')),
                ('pañal_niño_xxg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pañal niño talla XXG')),
                ('leche_entera', models.PositiveIntegerField(blank=True, null=True, verbose_name='Leche entera')),
                ('leche_descremada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Leche descremada')),
                ('nat_100', models.PositiveIntegerField(blank=True, null=True, verbose_name='NAT 100')),
                ('balon_gas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Balon de gas 11 kg')),
                ('parafina', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parafina')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveIntegerField(verbose_name='ROL')),
                ('razon_social', models.CharField(blank=True, max_length=60, verbose_name='Razon social')),
                ('rut', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidad')),
                ('giro', models.CharField(blank=True, max_length=60, verbose_name='Giro')),
                ('calle', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numeracion', models.PositiveIntegerField(verbose_name='Numeracion')),
                ('tipo', models.CharField(choices=[('ALCOHOL', 'Alcohol'), ('COMERCIAL', 'Comercial'), ('ESTACIONADO', 'Estacionado'), ('INDUSTRIAL', 'Industrial'), ('MICROEMPRESA', 'Microempresa'), ('PROFESIONAL', 'Profesional')], default='', max_length=30, null=True, verbose_name='Tipo Patente')),
                ('trabajadores_pais', models.PositiveIntegerField(verbose_name='Trabajadores pais')),
                ('trabajadores_comuna', models.PositiveIntegerField(verbose_name='Trabajadores Comuna')),
                ('trabajadores_patente', models.PositiveIntegerField(verbose_name='Trabajadores Patente')),
                ('created', models.DateField()),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
    ]
