# Generated by Django 3.2.8 on 2021-12-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregasPandemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega_pandemia_archivo', models.FileField(upload_to='vis/data/pandemia/', verbose_name='Entrega Pandemia')),
            ],
        ),
        migrations.CreateModel(
            name='PatentesVehiculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_fabricacion', models.PositiveIntegerField(verbose_name='Trabajadores pais')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca del auto')),
                ('placa', models.CharField(max_length=30, verbose_name='Placa')),
                ('calle', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numeracion', models.PositiveIntegerField(verbose_name='Numeracion')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo del auto')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('codigo_sii', models.CharField(max_length=30, verbose_name='Codigo de SII')),
                ('forma_pago', models.CharField(choices=[('1RA CUOTA', '1er cuota'), ('2DA CUOTA', '2da cuota'), ('CONTADO', 'Contado'), ('OTRO', 'Otro')], default='', max_length=30, null=True, verbose_name='Forma de pago')),
                ('total_pagar', models.PositiveIntegerField(verbose_name='Total a Pagar')),
                ('año_permiso', models.PositiveIntegerField(verbose_name='Año de Permiso')),
                ('fecha_pago', models.DateField(verbose_name='fecha de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='PermisosCirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('rut', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidad')),
                ('nombres', models.CharField(blank=True, max_length=30, verbose_name='Nombres')),
                ('efectuo_tramite', models.CharField(blank=True, max_length=30, verbose_name='Efectuo Tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveIntegerField(verbose_name='ROL')),
                ('razon_social', models.CharField(blank=True, max_length=60, verbose_name='Razon social')),
                ('rut', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidad')),
                ('giro', models.CharField(blank=True, max_length=60, verbose_name='Giro')),
                ('calle', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numeracion', models.PositiveIntegerField(verbose_name='Numeracion')),
                ('tipo', models.CharField(choices=[('ALCOHOL', 'Alcohol'), ('COMERCIAL', 'Comercial'), ('ESTACIONADO', 'Estacionado'), ('INDUSTRIAL', 'Industrial'), ('MICROEMPRESA', 'Microempresa'), ('PROFESIONAL', 'Profesional')], default='', max_length=30, null=True, verbose_name='Tipo Patente')),
                ('trabajadores_pais', models.PositiveIntegerField(verbose_name='Trabajadores pais')),
                ('trabajadores_comuna', models.PositiveIntegerField(verbose_name='Trabajadores Comuna')),
                ('trabajadores_patente', models.PositiveIntegerField(verbose_name='Trabajadores Patente')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
    ]
