# Generated by Django 3.2.8 on 2021-12-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'ordering': ['created'], 'verbose_name': 'empresas', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='patentesvehiculares',
            options={'ordering': ['fecha_pago'], 'verbose_name': 'patentesvehiculares', 'verbose_name_plural': 'patentesvehiculares'},
        ),
    ]
