# Generated by Django 3.2.8 on 2022-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exencionaseo',
            name='porcentaje_exencion',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje de Exención'),
        ),
    ]
