# Generated by Django 3.2.8 on 2022-01-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('carga', '0002_auto_20211230_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/DOM/', verbose_name='Dom - Tramites y permisos')),
            ],
        ),
        migrations.CreateModel(
            name='CargaExencionAseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(upload_to='carga/exencion_aseo/', verbose_name='Exención pago derechos de aseo')),
            ],
        ),
        migrations.AlterField(
            model_name='empresas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tipo',
            field=models.CharField(max_length=30, null=True, verbose_name='Tipo Patente'),
        ),
        migrations.CreateModel(
            name='ExencionAseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.DateTimeField(verbose_name='Marca Temporal')),
                ('tipo_documento', models.CharField(choices=[('RUT', 'Rut'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='RUT', max_length=30, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Identidad')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Materno')),
                ('estado_civil', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Civil')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupación')),
                ('tramo_rsh', models.PositiveSmallIntegerField(verbose_name='Tramo RSH')),
                ('calle', models.CharField(blank=True, max_length=30, null=True, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('complemento_direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento de Dirección')),
                ('rol_propiedad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol Propiedad')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('paga_contribucion', models.CharField(choices=[('NO', 'No'), ('SI', 'Si'), ('OTRO', 'Otro')], max_length=5, null=True, verbose_name='Paga Contribucioens')),
                ('porcentaje_exencion', models.PositiveSmallIntegerField(verbose_name='Porcentaje de Exención')),
                ('causal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Causal de Exención')),
                ('adj_docu', models.URLField(verbose_name='Adjuntar Documentos')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres')),
                ('serie', models.PositiveIntegerField(verbose_name='Serie')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
        migrations.CreateModel(
            name='DOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.CharField(blank=True, max_length=60, null=True, verbose_name='Tramite')),
                ('manzana', models.CharField(blank=True, max_length=30, null=True, verbose_name='Manzana')),
                ('predio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Predio')),
                ('calle', models.CharField(blank=True, max_length=30, null=True, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('n_permiso', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Permiso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
    ]
