# Generated by Django 3.2.7 on 2021-10-05 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallesIndependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Calle ',
                'verbose_name_plural': 'Calles de Independencia',
                'ordering': ['calle'],
            },
        ),
        migrations.CreateModel(
            name='UV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_uv', models.PositiveIntegerField(verbose_name='Numero de U.V.')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Unidad Vecinal',
                'verbose_name_plural': 'Unidades Vecinales',
                'ordering': ['numero_uv'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('RUT', 'Rut'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='RUT', max_length=30, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de Identidad')),
                ('nombre_persona', models.CharField(max_length=30, verbose_name='Nombre Persona')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion_persona', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numero_direccion', models.PositiveIntegerField(verbose_name='Numeración')),
                ('complemento_direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento de Dirección')),
                ('telefono_persona', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo_persona', models.EmailField(max_length=40, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['created'],
            },
        ),
    ]
