# Generated by Django 3.2.8 on 2022-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='tipo_correo',
        ),
        migrations.AddField(
            model_name='telefono',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono Secundario'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='tipo_telefono_secundario',
            field=models.CharField(choices=[('MOVIL', 'Movil'), ('CASA', 'Casa'), ('TRABAJO', 'Trabajo'), ('OTRO', 'Otro'), ('NO APLICA', 'No Aplica')], default='NO APLICA', max_length=200, null=True, verbose_name='Tipo de Teléfono Secundario'),
        ),
    ]
