# Generated by Django 3.2.8 on 2022-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Avenida/Calle/Pasaje'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración'),
        ),
    ]
