# Generated by Django 3.2.8 on 2022-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=200, verbose_name='Avenida/Calle/Pasaje'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Numeración'),
        ),
    ]
