# Generated by Django 3.2.8 on 2022-11-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personainfosalud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='prevision',
        ),
    ]
