# Generated by Django 3.2.8 on 2022-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221124_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='personainfosalud',
            name='isapre',
            field=models.CharField(choices=[('NO APLICA', 'No Aplica'), ('BANMEDICA', 'Banmedica'), ('ISALUD', 'Isalud'), ('COLMENA', 'Colmena'), ('CONSALUD', 'Consalud'), ('CRUZBLANCA', 'Cruz Blanca'), ('CRUZ DEL NORTE', 'Cruz del Norte'), ('NUEVA MASVIDA', 'Nueva Masvida'), ('FUNDACION', 'Fundacion'), ('VIDA TRES', 'Vida Tres'), ('ESENCIAL', 'Esencial')], default='NO APLICA', max_length=30, null=True, verbose_name='Isapre'),
        ),
        migrations.AlterField(
            model_name='personainfosalud',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'Fonasa'), ('DIPRECA-CAPREDENA', 'Dipreca-Capredena'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=30, verbose_name='Prevision de Salud'),
        ),
    ]
