# Generated by Django 3.2.8 on 2022-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221128_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='certificado_compin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Compin'),
        ),
        migrations.AddField(
            model_name='persona',
            name='certificado_embarazo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Embarazo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='discapacidad',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='embarazo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Embarazo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='enfermedad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Enfermedad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEO/A', 'Soltero/a'), ('CASADO/A', 'Casado/a'), ('VIUDO/A', 'Viudo/a'), ('UNION CIVIL', 'Union Civil'), ('DIVORSIADO/A', 'Divorsiado/a')], default='MOVIL', max_length=200, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='persona',
            name='hijos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Hijos'),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_de_atencion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='lLugar De Atencion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='medicamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nacionalidad'),
        ),
    ]
