# Generated by Django 3.2.8 on 2022-11-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221128_0927'),
        ('core', '0007_auto_20221128_1011'),
    ]

    operations = [
    ]
