# Generated by Django 3.2.8 on 2022-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0006_auto_20221128_1239_0007_auto_20221128_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personainfosalud',
            name='comentarios',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentarios '),
        ),
    ]
