# Generated by Django 3.2.8 on 2022-12-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personainfosalud_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='lugar_de_atencion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar De Atencion'),
        ),
        migrations.AlterField(
            model_name='personainfosalud',
            name='comentarios',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentarios '),
        ),
        migrations.CreateModel(
            name='PersonaArchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='core/archivo_persona/%Y/%m/%d/')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Archivo de persona',
                'verbose_name_plural': 'Archivos de persona',
            },
        ),
    ]
