# Generated by Django 3.2.8 on 2022-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_personainfosalud_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='lugar_de_atencion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar De Atencion'),
        ),
    ]
