# Generated by Django 3.2.8 on 2022-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221201_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaarchivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_personas/%Y/%m/%d/'),
        ),
    ]
