# Generated by Django 3.2.8 on 2022-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_persona_lugar_de_atencion'),
        ('core', '0011_alter_personaarchivos_archivo'),
    ]

    operations = [
    ]
