# Generated by Django 3.2.8 on 2022-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20221204_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personainfosalud',
            name='isapre',
            field=models.CharField(choices=[('NO APLICA', 'No Aplica'), ('BANMEDICA', 'Banmedica'), ('ISALUD', 'Isalud'), ('COLMENA', 'Colmena'), ('CONSALUD', 'Consalud'), ('CRUZBLANCA', 'Cruz Blanca'), ('CRUZ DEL NORTE', 'Cruz del Norte'), ('NUEVA MASVIDA', 'Nueva Masvida'), ('FUNDACION', 'Fundacion'), ('VIDA TRES', 'Vida Tres'), ('ESENCIAL', 'Esencial')], default='NO APLICA', max_length=30, null=True, verbose_name='Isapre'),
        ),
    ]
