# Generated by Django 3.2.8 on 2021-12-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia_archivo', models.FileField(upload_to='vis/data/pandemia/', verbose_name='Archivo Farmacia')),
            ],
        ),
    ]
