# Generated by Django 3.2.8 on 2021-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visfarmacia',
            name='farmacia_archivo',
            field=models.FileField(upload_to='vis/data/farmacia/prueba/', verbose_name='Archivo Farmacia'),
        ),
    ]
