# Generated by Django 3.2.8 on 2021-12-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_alter_visfarmacia_farmacia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visfarmacia',
            name='farmacia_archivo',
            field=models.FileField(upload_to='vis/data/farmacia/', verbose_name='Archivo Farmacia'),
        ),
    ]
