# Generated by Django 3.2.8 on 2022-10-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodegavirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Stock_min', models.IntegerField(blank=True, null=True)),
                ('Stock_max', models.IntegerField(blank=True, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto')),
            ],
        ),
    ]
