# Generated by Django 3.2.7 on 2021-10-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='numero_identificacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='tipo_identificacion',
        ),
    ]
