# Generated by Django 3.1.7 on 2021-04-16 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobanteventa',
            options={'verbose_name': 'Comprobante Venta', 'verbose_name_plural': 'Comprobantes de Venta'},
        ),
        migrations.AlterModelOptions(
            name='productofarmacia',
            options={'ordering': ['p_a', 'dosis'], 'verbose_name': 'Producto Farmacia', 'verbose_name_plural': 'Productos de Farmacia'},
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productovendido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Vendida'),
        ),
        migrations.AlterField(
            model_name='productovendido',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.productofarmacia', verbose_name='Nombre Producto'),
        ),
    ]
