# Generated by Django 3.2.8 on 2022-12-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='comprobante_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.comprobanteventa', verbose_name='Venta asociada'),
        ),
    ]
