# Generated by Django 3.1.7 on 2021-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_auto_20210415_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='numero_identificacion',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
