# Generated by Django 3.2.8 on 2022-10-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_bodegavirtual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegavirtual',
            options={'verbose_name': 'Bodega Virtual', 'verbose_name_plural': 'Bodega Virtual'},
        ),
        migrations.AlterModelTable(
            name='bodegavirtual',
            table='bodegavirtual',
        ),
    ]
