# Generated by Django 3.2.8 on 2021-11-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_auto_20211008_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='receta',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='receta_medica'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='dosis',
            field=models.CharField(max_length=200, null=True, verbose_name='Dosis del Producto'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='marca_producto',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='n_lote',
            field=models.CharField(max_length=200, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='p_a',
            field=models.CharField(max_length=200, null=True, verbose_name='Componente Activo'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='presentacion',
            field=models.CharField(max_length=200, null=True, verbose_name='Presentacion del Producto'),
        ),
    ]
