# Generated by Django 3.2.8 on 2022-10-19 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_auto_20221014_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegavirtual',
            name='Stock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
