# Generated by Django 3.2.8 on 2022-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_alter_bodegavirtual_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegavirtual',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock del producto'),
        ),
        migrations.AlterField(
            model_name='bodegavirtual',
            name='stock_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock maximo del producto'),
        ),
        migrations.AlterField(
            model_name='bodegavirtual',
            name='stock_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock minimo del producto'),
        ),
        migrations.AlterModelTable(
            name='bodegavirtual',
            table='BodegaVirtual',
        ),
    ]
