# Generated by Django 3.2.1 on 2021-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_auto_20210502_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='f_ven',
            field=models.CharField(default='03/11/2021', max_length=10, verbose_name='Fecha vencimiento'),
        ),
    ]
