# Generated by Django 3.2.1 on 2021-05-12 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0005_productofarmacia_f_ven'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='n_lote',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero de Lote'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='precio',
            field=models.PositiveIntegerField(default=1, verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='f_ven',
            field=models.DateTimeField(verbose_name='Fecha de vencimiento'),
        ),
    ]
