# Generated by Django 3.2.8 on 2022-10-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_auto_20221020_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodegavirtual',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='Laboratorios',
        ),
        migrations.RemoveField(
            model_name='ordeningresoproducto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='productoingresado',
            name='farmaceuta',
        ),
        migrations.RemoveField(
            model_name='productoingresado',
            name='n_venta',
        ),
        migrations.RemoveField(
            model_name='productoingresado',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='bodegavirtual',
        ),
        migrations.DeleteModel(
            name='OrdenIngresoProducto',
        ),
        migrations.DeleteModel(
            name='ProductoIngresado',
        ),
    ]
