# Generated by Django 3.2.8 on 2022-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_auto_20221021_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productofarmacia',
            name='bioequivalencia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bioequivalencia'),
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='cenabast',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cenabast'),
        ),
    ]
