# Generated by Django 3.2.8 on 2022-10-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0010_alter_productofarmacia_bioequivalencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovendido',
            name='farmaceuta',
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='bioequivalencia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bioequivalencia'),
        ),
    ]
