# Generated by Django 3.2.8 on 2022-11-01 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_auto_20221027_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.FileField(blank=True, null=True, upload_to='farmacia/receta_medica/%Y/%m/%d/')),
                ('comprobante_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.comprobanteventa', verbose_name='Venta asociada')),
            ],
        ),
    ]
