# Generated by Django 3.2.8 on 2022-11-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_recetas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetas',
            options={'verbose_name': 'Receta Medica', 'verbose_name_plural': 'Recetas Medicas'},
        ),
    ]
