# Generated by Django 3.2.8 on 2022-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_alter_recetas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovendido',
            name='precio_venta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Producto de la Venta'),
        ),
    ]
