# Generated by Django 3.2.8 on 2022-11-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmacia', '0014_productovendido_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
    ]
