# Generated by Django 3.2.8 on 2022-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_auto_20221024_1347'),
        ('farmacia', '0015_alter_comprobanteventa_farmaceuta'),
    ]

    operations = [
    ]
