# Generated by Django 3.2.8 on 2022-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_alter_comprobanteventa_farmaceuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productofarmacia',
            name='active',
        ),
    ]
