# Generated by Django 3.2.8 on 2022-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_remove_productofarmacia_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Laboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.RemoveField(
            model_name='productofarmacia',
            name='precio',
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='cenabast',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cenabast'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='proveedor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Proveedor'),
        ),
    ]
