# Generated by Django 3.2.8 on 2022-11-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0017_auto_20221123_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='farmacia.laboratorios', verbose_name='Laboratorio'),
            preserve_default=False,
        ),
    ]
