# Generated by Django 3.2.8 on 2022-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0018_productofarmacia_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='precio',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Precio Producto'),
        ),
    ]
