# Generated by Django 3.2.8 on 2021-12-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_requerimiento', models.PositiveIntegerField(null=True, verbose_name='Numero de requermineto')),
                ('identidad', models.CharField(choices=[('1', 'Identidad'), ('2', 'Seudonimo'), ('3', 'Anonimo')], default='3', max_length=1, verbose_name='Identidad')),
                ('numero_identificacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Identidad')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Denunciado')),
                ('apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Denunciado')),
                ('calle', models.CharField(max_length=30, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('interseccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intersección')),
                ('delito_social', models.CharField(blank=True, choices=[('1', 'Robo con violencia e intimidación'), ('2', 'Robo en lugar no habitado'), ('3', 'Hurto'), ('4', 'Robo por sorpresa'), ('5', 'Robo de vehículo'), ('6', 'Homicidio'), ('7', 'Violación'), ('8', 'Robo desde vehículo')], max_length=1, null=True, verbose_name='Delito de mayor connotación social')),
                ('violencia_intrafamiliar', models.CharField(blank=True, choices=[('1', 'VIF contra mujer'), ('2', 'VIF contra hombre'), ('3', 'VIF contra NNA'), ('4', 'VIF contra adulto/a mayor')], max_length=1, null=True, verbose_name='Violencia Intrafamiliar')),
                ('incivilidades', models.CharField(blank=True, choices=[('1', 'Amenaza'), ('2', 'Riñas callejeras'), ('3', 'Comercio informal'), ('4', 'Consumo de alcohol y/o drogas en vía pública'), ('5', 'Daños'), ('6', 'Desordenes'), ('7', 'Ruidos molestos'), ('8', 'Otro')], max_length=1, null=True, verbose_name='Incivilidades')),
                ('abuso_sexual', models.CharField(blank=True, choices=[('1', 'Abusos sexuales'), ('2', 'Abusos sexuales mayor 14 años'), ('3', 'Abusos sexuales menor 14 años'), ('4', 'Otros delitos sexuales')], max_length=1, null=True, verbose_name='Abusos sexuales')),
                ('accidente', models.CharField(blank=True, choices=[('1', 'Accidente de tránsito'), ('2', 'Incendio')], max_length=1, null=True, verbose_name='Accidentes e incendios')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('prioridad', models.CharField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Leve')], default='1', max_length=1, verbose_name='Prioridad')),
                ('resolucion', models.CharField(choices=[('1', 'Cursar infracción'), ('2', 'Proceso judicial'), ('3', 'Derivación Área Prevención'), ('4', 'Territorial'), ('5', 'Atención a Víctimas'), ('6', 'Convivencia'), ('7', 'Derivación Unidad especializada'), ('8', 'Intramunicipal ¿cuál?'), ('9', 'Extramunicipal ¿cuál?')], default='1', max_length=1, verbose_name='Forma de resolución del requerimiento')),
                ('des_resolucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Cuál?')),
                ('estatus', models.CharField(choices=[('1', 'Recepcionado'), ('2', 'Pendiente'), ('3', 'En Curso'), ('4', 'Resuelto')], default='1', max_length=1, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
